version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.11.0

    steps:
      - checkout

      - run:
          name: install
          command: npm install

      - run:
          name: eslint
          command: npm run lint

      - run:
          name: build
          command: npm run build