#!/bin/bash
# https://gist.github.com/rashtay/328da46a99a9d7c746636df1cf769675

echo "[pre-commit]: START"

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM)
ESLINT="$(git rev-parse --show-toplevel)/node_modules/.bin/eslint"

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

PASS=true

# Check for eslint
if [[ ! -x "$ESLINT" ]]; then
    echo "[pre-commit]: Please install eslint"
  exit 1
fi

for FILE in $STAGED_FILES
do
  if ! [[ "$FILE" =~ .json$ ]]; then
    "$ESLINT" "$FILE"
    if ! [[ "$?" == 0 ]]; then
      echo "[pre-commit]: ERROR: $FILE "
      PASS=false
    else
      echo "[pre-commit]: OK: $FILE "
    fi
  fi
done

echo "[pre-commit]: eslint review finished"

if ! $PASS; then
  echo "[pre-commit]: Fix eslint errors and try again"
  exit 1
fi

echo "[pre-commit]: Commit succeeded"
exit 0
