#!/bin/bash
# Prevents force-pushing to master
# This file needs execution permissions

# https://gist.github.com/pixelhandler/5718585#gistcomment-840997
# https://gist.github.com/pixelhandler/5718585#gistcomment-1390358

echo "[pre-push]: START"
PUSH_COMMAND=`ps -ocommand= -p $PPID`
PROTECTED_REMOTE_BRANCHES="(master|release-*|patch-*)"

# Check the file of example pre-push.sample to get variables
while read local_ref local_sha remote_ref remote_sha
do
  echo "[pre-push]: Trying to push towards the branch $remote_ref"
  BRANCH_TO_PUSH="$remote_ref"
  if [[ "$BRANCH_TO_PUSH" =~ $PROTECTED_REMOTE_BRANCHES ]]; then
      echo "[pre-push]: Failed to push to \"$BRANCH_TO_PUSH\" because is blocked by the repository owner"
      exit 1
  fi
done

echo "[pre-push]: Push to $BRANCH_TO_PUSH succeeded"
exit 0
